### ISSUE TITLE
Reg:- setColProperty not working

### ISSUE THREAD

**Issue by arasub** [mgallegos/laravel-jqgrid#17]
Hi mgallegos,

  It was a great one you have did for the laravel and thanks for this wonderful stuff.
Let me come to the problem,

Do we have the setColProperty ? if not how we can implement the dropdown with the select and have with inline edit?

thanks
arasu.b

**Comment by arasub** [comment]
I like to know did we started implementing the subgrid ?

**Comment by mgallegos** [comment]
Sorry for my late reply, here is an example of how you can implement it:

```javascript
<script type='text/javascript'>
   var lastsel2;
   function onSelectRow(id)
   {
      if(id && id!==lastsel2){
       //#BookGrid this is your grid id
       jQuery('#BookGrid').restoreRow(lastsel2);
       jQuery('#BookGrid').editRow(id,true);
       lastsel2=id;
    }
   }
</script>
```
```php
GridRender::setGridId("BookGrid")
...
->setGridEvent('onSelectRow','onSelectRow')
->addColumn(array('label' => 'Language','index' => 'language', 'align' => 'center', 'width' => 90, 'editable' => true, 'editoptions' => array('value' => 'E:English;S:Spanish;G:German'), 'edittype' => 'select', 'formatter' => 'select', 'editrules' => array('required' => true)))
```
Let me know if you have any question!

**Comment by arasub** [comment]
thanks i figured out, i managed to do the rending part with using jQuery("#divid").jqGrid() and this also helped me to implement the subgrid.

Interested to know if we done with the subgrid and inline edit.

thanks
arasu.b

**Comment by arasub** [comment]
Also struck with inline edit with CSRF blocking. I'm working on the same. do let me know if we have methods to handle CSRF.

thanks
arasu.b

**Comment by arasub** [comment]
Hi, 

While usign the JQgrid aftersubmit not working.
                      afterSubmit:function(response, postdata) {alert("it Works");
                        return isError(response.responseText);

                    },

Thanks
arasu.b

**Comment by mgallegos** [comment]
> Also struck with inline edit with CSRF blocking. I'm working on the same. do let me know if we have methods to handle CSRF.

This is what I do:

```php
->setGridOption('postData', array('_token' => Session::token()))
```

> While usign the JQgrid aftersubmit not working.

Please show me how are you setting this event using "GridRender::"
