### ISSUE TITLE
laravel-jqgrid para laravel 5.*

### ISSUE THREAD

**Issue by arceYerson** [mgallegos/laravel-jqgrid#18]
Hola mgallegos muy buen trabajo con lo del laravel-jqgrid ya me he acostumbrado a usarlo, pero ahora que estoy actualizando a laravel 5 veo que que tu paquete no lo soporta te ruego encarecidamente que lo actualices, o hay alguna forma que pueda instalarlo en L5,
Desde ya muchas gracias por su respuesta.

**Comment by mgallegos** [comment]
En la rama "dev-master" estoy trabajando para que funcione con L5, por el momento solo le he actualizado las dependencias, pero no he probado si funciona.

He estado un poco ocupado y por eso aún no lo he terminado, pero espero hacerlo en los próximos días.

**Comment by arceYerson** [comment]
Muchas gracias por tu respuesta, Se instala correctamente pero estoy obteniendo el siguiente error: Call to undefined method [package]

**Comment by arceYerson** [comment]
Buen día, una consulta donde puede descargar el codigo fuente (si es posible) de tu paquete dev de laravel-jqgrid, quiero intentar adaptarlo a laravel 5 he estado investigando sobre la creacion de paquetes.
Un saludo

**Comment by mgallegos** [comment]
Clona el repositorio [aquí en GitHub] (https://github.com/mgallegos/laravel-jqgrid) y si lo haces funcionar puedes enviarme un pull-request.

Disculpa por no haber podido dedicarle tiempo aún a tus solicitud de que funcione con L5, ya varias personas me lo han pedido, pero en cuanto tenga el tiempo lo haré.

**Comment by mgallegos** [comment]
Ya actualice el paquete para que funcione con L5, enjoy!

**Comment by arceYerson** [comment]
Muchas gracias
