### ISSUE TITLE
GridRender is not working... jQuery(...).jqgrid is not a function

### ISSUE THREAD

**Issue by mytrix-technology** [mgallegos/laravel-jqgrid#19]
Hello Martin Gallegos...
I try your laravel-jqgrid but I have a problem.
I can't load the grid table because jQuery(...).jqgrid is not a function..
I follow your instruction at http://www.mariogallegos.com/tutorials/crud-custom-form but the grid is not loading...
If I follow this instruction http://www.trirand.com/jqgridwiki/doku.php?id=wiki:first_grid, it works.

Why function GridRender::setGridId("...") is not working???

Can you help me???

**Comment by mgallegos** [comment]
It seems that you haven't included the jquery and jqgrid javascript libraries.

**Comment by mytrix-technology** [comment]
I have included jquery and jqgrid javascript library but function GridRender::setGridId("...") still not working...

Why is this happen??

**Comment by mgallegos** [comment]
May I see the full error message?

**Comment by DragosBobolea** [comment]
The problem is that if you load jQuery AFTER the GridRender, and the javascript generated by GridRender does not wait for $(document).ready, it won't find jqGrid.

Even if you load it before in your source, there's no guarantee it won't fail anyway

I've hit this problem myself now
