### ISSUE TITLE
Problemas con el token de validación

### ISSUE THREAD

**Issue by arceYerson** [mgallegos/laravel-jqgrid#21]
Estoy teniendo este problema "TokenMismatchException in VerifyCsrfToken.php line 53" y es porque no se esta enviando un token de validacion con "setGridOption('url',URL::to('/grid-data'))"  como se podria añadirlo para no tener que desactivarlo.

**Comment by mgallegos** [comment]
Yo lo hago de esta forma:

```php
->setGridOption('postData', array('_token' => Session::token()))
```

**Comment by arceYerson** [comment]
Excelente funciono de maravilla, Muchas gracias
