### ISSUE TITLE
Problema al mostrar los datos en la grilla

### ISSUE THREAD

**Issue by dquirozgruposgd** [mgallegos/laravel-jqgrid#24]
Hola mgallegos, primero que nada muchas gracias por el desarrollo de este framework. Te cuento que lo implemente en laravel 4.2 y no he tenido ningun problema. Ahora lo estoy implementando en laravel 5,y luego de realizar todos los cambios necesarios logre mostrar la grilla pero sin las columnas de datos. Se que los datos estan pasando a la vista ya que puedo exportar como un xls los datos y aparecen en el excel, pero no entiendo por que no puedo verlos en la grilla.

de ante mano muchas gracias!

**Comment by mgallegos** [comment]
> primero que nada muchas gracias por el desarrollo de este framework

De nada, me alegro que te sea útil.

> aparecen en el excel, pero no entiendo por que no puedo verlos en la grilla.

Que raro el problema que tienes, podrías mostrarme el código con el que generas el Grid y el código de tu "repository class".

**Comment by dquirozgruposgd** [comment]
gracias por la rapida respuesta, estoy utilizando los mismos codigos q uno de tus tutoriales pero modificados para q corran en laravel 5.

Repository:

<?php

namespace App;
use \Illuminate\Support\Facades\DB;
use Illuminate\Database\Eloquent\Model as Eloquent;
use Mgallegos\LaravelJqgrid\Repositories\EloquentRepositoryAbstract;
 
class InvoiceRepository extends EloquentRepositoryAbstract {
 
  public function __construct()
  {
    $this->Database = new Invoice();
 
    $this->visibleColumns = array('id', 'number', 'date', 'client', 'country');
 
    $this->orderBy = array(array('id', 'asc'), array('client','desc'));
  }
}


grid:

@extends('base')

@section('container')
	{{
GridRender::setGridId("InvoicesGrid")
  ->enableFilterToolbar()
  ->setGridOption('url', URL::to('/invoice-grid'))
  ->setGridOption('rowNum', 5)
  ->setGridOption('width', 750)
  ->setGridOption('height', 115)
  ->setGridOption('rowList', array(5,10,15,20))
  ->setGridOption('caption', 'Invoices')
  ->setGridOption('viewrecords', true)
    ->addColumn(array('name'=>'id', 'index'=>'id', 'align'=>'center', 'hidden' => true))
  ->addColumn(array('label'=>'Invoice #','index'=>'number', 'align'=>'center', 'width' => 30))
  ->addColumn(array('label'=>'Date', 'align'=>'center','index'=>'date', 'width' => 60 ))
  ->addColumn(array('label'=>'Client','index'=>'client', 'align'=>'right'))
  ->addColumn(array('label'=>'Country','index'=>'country', 'align'=>'right'))
  ->renderGrid()
}}
@stop

gracias!. saludos

**Comment by mgallegos** [comment]
Puede ser que la validación del del token csrf te esta dando problema, en L5 viene activada por defecto. Proba agregando la siguiente opción:

```php
->setGridOption('postData',array('_token' => Session::token()))

**Comment by dquirozgruposgd** [comment]
muchas gracias me has salvado, estuve con este problema 2 dias enteros. muchas gracias! te pasaste!
