### ISSUE TITLE
Getting empty table

### ISSUE THREAD

**Issue by abiliomp** [mgallegos/laravel-jqgrid#25]
Hi! I followed your tutorial with my own database model, but the table renders empty. Additionally the server responds "500 Internal Server Error" to the POST request. What could be wrong?

**Comment by mgallegos** [comment]
Take a look to your server error log file, I need for information in order to help you!

**Comment by abiliomp** [comment]
Sorry, I forgot to put that. Here is the main message:
[2015-09-04 23:45:05] development.ERROR: exception 'Illuminate\Session\TokenMismatchException' in C:\vhosts\omniweb\vendor\laravel\framework\src\Illuminate\Foundation\Http\Middleware\VerifyCsrfToken.php:53

**Comment by abiliomp** [comment]
I think that I should put the csrf_token() call somewhere, but since the GridRender makes the grid form, I have no clue were to put it.

**Comment by mgallegos** [comment]
Add the following grid option:

```php
->setGridOption('postData', array('_token' => csrf_token()))
```

**Comment by abiliomp** [comment]
Thanks a lot Mario! Now it seems to be working. I don't know if I should open another topic, but here is my problem. I have several fields from other models  (dereference foreign keys) that I want to show in the same table (e.g.: field user_id => users table, and I want to show user->name in the table). How do I do that?

**Comment by mgallegos** [comment]
If what you mean is that you need to join more than one table, take a look at this code (I took it from [one of my tutorials](http://www.mariogallegos.com/tutorials/pivot-grid))
```php
<?php
use Illuminate\Database\DatabaseManager as DatabaseManager;
 
use Mgallegos\LaravelJqgrid\Repositories\EloquentRepositoryAbstract;
 
class InvoiceItemRepository extends EloquentRepositoryAbstract {
 
  public function __construct(DatabaseManager $DatabaseManager)
  {
    $this->Database = $DatabaseManager->table('DEMO_Invoice_Item')
                                      ->join('DEMO_Invoice', 'DEMO_Invoice_Item.invoice', '=', 'DEMO_Invoice.id');
 
    $this->visibleColumns = array('number','description', 'unitCost', 'quantity', 'total','DEMO_Invoice.id', 'country', 'category');
 
    $this->orderBy = array(array('DEMO_Invoice_Item.id', 'asc'));
  }
}
```

**Comment by abiliomp** [comment]
Thanks again!! I'm very sorry to bother you, but I followed your first tutorial and got the "undefined $app" variable message. So far I figured out that this variable is set on start of the PHP application. But for some reason during the routes loading gets missed. And again any ideas? Sorry man

**Comment by abiliomp** [comment]
Finally I got this one on my own. 

$app = $this->app

Many thanks Mario! Great library!

**Comment by mgallegos** [comment]
You're wellcome and It's no bother at all!
