### ISSUE TITLE
Excel and CSV buttons not working

### ISSUE THREAD

**Issue by abiliomp** [mgallegos/laravel-jqgrid#26]
Hi Mario! Just after finishing the first part of my practice with your library I found a new problem. My example isn't exporting the data to Excel or CSV. 
It seems to be a Javascript issue. Here is what FireBug tells me:

TypeError: jQuery(...).getGridParam is not a function

And it references to the following generated Javascript

jQuery("#AccLogsGridModel").val(JSON.stringify(jQuery("#AccLogsGrid").getGridParam("colModel")));

I spend the past hour trying to fix it without results. Any idea? Thanks!

**Comment by mgallegos** [comment]
What's version of jqgrid are you using?

I recommend you to download the latest available.

**Comment by abiliomp** [comment]
Hi Mario! Sorry for the delay. I'm using jqGrid's last version (v4.8). How can I debug this feature?

**Comment by mgallegos** [comment]
The only thing that comes to mind is that you might have another element with the same id "AccLogsGrid"

**Comment by KrasilnikovKB** [comment]
same problem :((

`
    {!! Html::style('/css/jquery-ui/jquery-ui.min.css') !!}
    {!! Html::style('/css/jqgrid/ui.jqgrid.css') !!}

    {!! Html::style('/css/jqgrid/searchFilter.css') !!}
    {!! Html::style('/css/jqgrid/ui.multiselect.css') !!}

    {!! Html::script('/js/jquery-2.2.1.min.js') !!}
    {!! Html::script('/js/jquery-ui.min.js') !!}
    {!! Html::script('/js/grid.locale-ru.js') !!}
    {!! Html::script('/js/jquery.jqGrid.min.js') !!}

    {!! Html::script('/js/jqgrid/plugins/grid.addons.js') !!}
    {!! Html::script('/js/jqgrid/plugins/grid.postext.js') !!}
    {!! Html::script('/js/jqgrid/plugins/grid.setcolumns.js') !!}
    {!! Html::script('/js/jqgrid/plugins/jquery.contextmenu.js') !!}
    {!! Html::script('/js/jqgrid/plugins/jquery.searchFilter.js') !!}
    {!! Html::script('/js/jqgrid/plugins/jquery.tablednd.js') !!}
    {!! Html::script('/js/jqgrid/plugins/ui.multiselect.js') !!}
`

`
/* 
* jqGrid  5.0.2  
* Copyright (c) 2008, Tony Tomov, tony@trirand.com 
*  License: http://guriddo.net/?page_id=103334 
*
* Modules: grid.base.js; jquery.fmatter.js; grid.common.js; grid.formedit.js; grid.filter.js; grid.inlinedit.js; grid.celledit.js; jqModal.js; jqDnR.js; grid.subgrid.js; grid.grouping.js; grid.treegrid.js; grid.pivot.js; grid.import.js; grid.utils.js; grid.jqueryui.js;
*/
`

when i press XLS or CSV button in chrome-console geting error:
![image](https://cloud.githubusercontent.com/assets/16627494/14708528/3d33a18e-07d4-11e6-8621-b5c995b0661a.png)
