### ISSUE TITLE
save() not working

### ISSUE THREAD

**Issue by shahin1979** [mgallegos/laravel-jqgrid#27]
I always geting error,'Something went wrong, please try again later.' at the below section:

type: 'POST',
                        //Creates an object from form fields.
                        //The "formToObject" is a custom helper function, its definition
                        //can be foound in the public/assets/tutorial/js/helpers.js script.
                        data: JSON.stringify($('#book-form').formToObject('')),
                        dataType : 'json',
                        url: url,
seems JSON.stringify not able to prepare data. please help me.

**Comment by mgallegos** [comment]
Please use your browser inspection tools to get more information about the error.

**Comment by shahin1979** [comment]
Thank You Very Much. 
I follow as you suggested and found the problem. as bellow
at the Eloquent Class, used

$data['length'] = str_replace(',', '', $data['length']);

but it says undifined methed length is used. I just make the line as comment and it works fine now. 

please make your comment about that.

**Comment by mgallegos** [comment]
That's wear because there is no method length in that code line.

The variable $data['length'] is referring to the form field of the tutorial with the same name.

**Comment by shahin1979** [comment]
Thank You Again. Need another help from you. How I can forward a selectd grid row field data to the next page to do some other activities?

I want to add a next button and when a grid data is selected and click 'next' that selected row data have to be available to get. 

Thank You in advance.

**Comment by mgallegos** [comment]
This is the javascript code to get the selected row data:

```javascript
var rowData = $('#grid-id').getRowData($('#grid-id').jqGrid('getGridParam', 'selrow'));
```

**Comment by shahin1979** [comment]
Thank you for your kind cooperation. 
would you please letting me know, how i can use where clause in 'repository class'?

for example: the book repository class is:
use Illuminate\Database\Eloquent\Model;
 
use Mgallegos\LaravelJqgrid\Repositories\EloquentRepositoryAbstract;
 
class BookRepository extends EloquentRepositoryAbstract {
 
public function __construct(Model $Model)
{
$this->Database = $Model;
 
$this->visibleColumns = array('id', 'name', 'description', 'author', 'publisher', 'language', 'length', 'asin');
 
$this->orderBy = array(array('id', 'asc'));
}
}

I want to use where clause here to show data in grid. something like 
'where name in( 'Textbook'). how i can do it?

**Comment by mgallegos** [comment]
You can do it likes this:

```php
$this->Database = $Model->whereIn('name', array('Textbook 1', 'Textbook 2'));
```
