### ISSUE TITLE
I'm new in laravel and I am using jqGrid. I have included all .css and .js files as in example, but I'm still having a parse error on my view. 

### ISSUE THREAD

**Issue by brigite** [mgallegos/laravel-jqgrid#32]
<div id="grid-section" class="app-grid collapse in">
        {{
        GridRender::setGridId('WarehouseGrid')
          ->enablefilterToolbar(true, false)
          ->hideXlsExporter()
          ->hideCsvExporter()
          ->setGridOption('url',URL::to('/warehouse-grid'))
          ->setGridOption('rowNum', 10)
          ->setGridOption('rownumbers', true)
          ->setGridOption('width', 750)
          ->setGridOption('height', 225)
          ->setGridOption('rowList',array(10,20,30))
          ->setGridOption('caption','Warehouse')
          ->setGridOption('viewrecords',true)
          ->setGridEvent('onSelectRow', 'onSelectRowEvent')
          ->addColumn(array('index' => 'warehouse_id', 'hidden' => true))
          ->addColumn(array('label' => 'Magazina', 'index'=>'warehouse_name'))
          ->addColumn(array('label' => 'Pershkrimi','index' => 'warehouse_description'))
          ->addColumn(array('label' => 'Data krijimit','index' => 'created_at'))
          ->renderGrid();
        }}
    </div>

**Comment by mgallegos** [comment]
Try using {!! !!} and omit the ;
