### ISSUE TITLE
Advanced search - OR conditions in filter

### ISSUE THREAD

**Issue by mohinlakdawala** [mgallegos/laravel-jqgrid#33]
Hi, I am trying to implement the advanced search functionality with this. Does this not support the case when groupOp is selected as 'any' for the filters ?

**Comment by mgallegos** [comment]
No it does not, at the moment everything is assume as an "AND" condition, you can see the code here:

[https://github.com/mgallegos/laravel-jqgrid/blob/master/src/Mgallegos/LaravelJqgrid/Repositories/EloquentRepositoryAbstract.php#L201](https://github.com/mgallegos/laravel-jqgrid/blob/master/src/Mgallegos/LaravelJqgrid/Repositories/EloquentRepositoryAbstract.php#L201)
