### ISSUE TITLE
extendeble export

### ISSUE THREAD

**Issue by KrasilnikovKB** [mgallegos/laravel-jqgrid#38]
may make the export function of the outside from JqGridJsonEncoder / encodeRequestedData ?

perform the necessary action depending on the value $postedData['exportFormat']

I wanted to do data export using [templates](https://github.com/PHPOffice/PHPWord/blob/develop/samples/Sample_07_TemplateCloneRow.php), but unfortunately I do not understand anything in Laravel facades/providers/containers :(((

obviously it requires a mechanism for extending the export methods
all hope for you

**Comment by mgallegos** [comment]
Sounds like a good idea, I believe it can be done.

I marking this issue as an enhancement.
