### ISSUE TITLE
filter toolbar search not working after hosted in domain

### ISSUE THREAD

**Issue by sureshamk** [mgallegos/laravel-jqgrid#4]
Filter tool bar option is working fine in local . after i moved to hosted for live then i am not able get search result . but the query is posted .

**Comment by Eslam87** [comment]
Following the tutorial "Building a Pivot Grid and handling jqGrid" i get an error. Laravel say to me $app is undefined. The piece of code that generate the problem is this :
Route::post('/invoice-item-grid', function() use ($app)
{
GridEncoder::encodeRequestedData(new InvoiceItemRepository($app['db']), Input::all());
});
any way i want to do join query and some staff like that 
Model::find(1)
Model::where('id','=',1)
in Repositry file or any way to do that ?

**Comment by mgallegos** [comment]
For Laravel 5, do the following:

```php
Route::post('/invoice-item-grid', function() use ($app)
{
GridEncoder::encodeRequestedData(new InvoiceItemRepository($app['db']), Input::all());
});
```
If the query you want to do is for showing data in the grid, you should do it inside the "Repository Class"(in this case, in InvoiceItemRepository)

**Comment by tglx** [comment]
Congratulations Mario for the Grid. I use Laravel 4.2.16. I want to query (from the server) the database filtered (e.g ->with('id_client','=','3')).

How could I send a POST parameter ?
Maybe method 1:
        {{GridRender::setGridId("myGrid")
            ->setGridOption('url',URL::to('/myLink-data-from-server'))
            
            something like
            ->setPostParameter('id_client','=','3')
            or
            ->setFilterParameter('id_client','=','3')

Maybe method 2:
Initialize the filter <input type='text'> AND run the query (->renderGrid();) AND hide the filter <input type='text') and hide the entire column.


Thank you for your time & response ...

**Comment by mgallegos** [comment]
To send a POST parameter when the grid is created, we must simulate that we are using the filtered toolbar, in your case it should look like this:

```php
->setGridOption('postData',array('filters'=>"{'groupOp':'AND','rules':[{'field':''id_client','op':'eq','data':'3}]}"))
```

In the turorial [Building a Pivot Grid and handling jqGrid events](http://www.mariogallegos.com/tutorials/pivot-grid) you can see an example of how to work with parameters.

**Comment by Eslam87** [comment]
I'm using custom form using Laravel jqGrid package 
what about server side validation ...I tried to do Request validation or class validator but not working 
any help please ?

**Comment by tglx** [comment]
THANK you Mario! It worked! + in your link ([Building a Pivot ...](http://www.mariogallegos.com/tutorials/pivot-grid)), at Step 6 and row 12 I found the example!

**Comment by tglx** [comment]
I continue my scenario/situation: how do I keep the filter (WHERE id_client=3) when the user, complete in the FilterToolbar<input text> a value (and press Enter).

An other example, I have
<?php
GridRender::setGridId("myGrid")
            ->enablefilterToolbar(true, true) // show/create ToggleButton and show/create ClearButton
?>

And when the user (of the webpage) press the ClearButton (clear all the Filters completed by the user) I need to show the grid Filtered (WHERE id_client=3).
(I repet the question) How do I keep the filter, in this situation ?

THANK you Mario for your TIME & response :-)

**Comment by mgallegos** [comment]
The tutorial also shows you what you need, the first step is to define the following javascript events:

```javascript
function onLoadCompleteEvent(data)
{
  $(this).jqGrid('footerData','set', {'quantity': 'Invoice Total:', 'total': $(this).jqGrid('getCol', 'total', false, 'sum')});
}
 
function beforeClearEvent()
{
  $(this).jqGrid('setGridParam', {'postData':{"filters":"{'groupOp':'AND','rules':[{'field':'DEMO_Invoice.id','op':'eq','data':'" + $('#selectedInvoiceId').val() + "'}]}"}});
}
 
function afterClearEvent()
{
  //The id of all "filter toolbar" input text are formed by the prefix "gs_" and the column name.
  $('#gs_InvoiceId').val($('#selectedInvoiceId').val());
}
```

Then you need to add these events to your grid:
```php
->setFilterToolbarEvent('beforeClear','beforeClearEvent')
->setFilterToolbarEvent('afterClear','afterClearEvent')
```
Hope this helps!
