### ISSUE TITLE
Error Model On Laravel 5.2

### ISSUE THREAD

**Issue by mirul16** [mgallegos/laravel-jqgrid#41]
Hi Mario,

I've got error like below message on implementation for Laravel 5.2 : 

FatalErrorException in routes.php line 40:
Class 'InvoiceRepository' not found

Could you please advice for the solution?

**Comment by mgallegos** [comment]
Sorry for the late response, the class you mentioned is used in the turorials.

Are you sure, you have included it?

I do realize that I have to update the tutorial for Laravel 5, sorry about that.
