### ISSUE TITLE
Export XLS file problem

### ISSUE THREAD

**Issue by amittier5** [mgallegos/laravel-jqgrid#44]
Hello I have used your laravel package.when i am trying to export data as XLS, get a wrong format.can you please let me know what are issues?
Attached file as below as zip format.
[AssociationGrid(1).xls.zip](https://github.com/mgallegos/laravel-jqgrid/files/385869/AssociationGrid.1.xls.zip)

**Comment by dquirozgruposgd** [comment]
Im facing the same issue, cant figure it out.

**Comment by mgallegos** [comment]
If you remove the .zip extension, does it work?

**Comment by amittier5** [comment]
can you please unzip give files.XLS file inside that zip file.
