### ISSUE TITLE
jqGridRender.php

### ISSUE THREAD

**Issue by yalmar** [mgallegos/laravel-jqgrid#54]
Dear Mario, 

Tengo el siguiente problema

 ErrorException (E_ERROR)

Argument 1 passed to Mgallegos\LaravelJqgrid\Renders\JqGridRender::getJavascriptExportFunctionCode() must be an instance of Mgallegos\LaravelJqgrid\Renders\string, string given, called in F:\easyphp56z\eds-www\tutorial\vendor\mgallegos\laravel-jqgrid\src\Mgallegos\LaravelJqgrid\Renders\JqGridRender.php on line 1026 and defined (View: F:\easyphp56z\eds-www\tutorial\app\views\tutorial.blade.php) 

Opté por comentar esa linea (1026) y funciona normalmente.
No se si esa linea 
$script .= $this->getJavascriptExportFunctionCode( substr($key, 0, -1*strlen('ButtonVisible') ) );
hace alguna cosa en especial, no se por que da ese error en mi proyecto

**Comment by mgallegos** [comment]
Perdón por la respuesta tardía, voy a revisarlo, porque esa una parte de un **pull request** que incluí al proyecto.

**Comment by mgallegos** [comment]
Fixed!
