### ISSUE TITLE
Bug: failure to json encode data rows containing UTF8 chars.

### ISSUE THREAD

**Issue by sroutier** [mgallegos/laravel-jqgrid#61]
Hello Mario,

First thanks a lot for your package. It is super helpful in making the jqGrid usable. I could not do it without your package.

I found a little problem in the way that the data rows are returned to the jqGrid, actually the problem is within json_encode(), but since we are not going to get that fixed anytime soon, we all have to deal with it manually. The root of the problem is that json_encode() silently fails when something happens that it does not like. In my case it was an UTF8 character in the data rows.

I have a fix and will submit a PR.
Let me know if  you have any questions.
Cheers. and Thanks again.

/s

**Comment by mgallegos** [comment]
You are welcome @sroutier, I merged your pull request, thanks  for your contribution!
