### ISSUE TITLE
Double click

### ISSUE THREAD

**Issue by manuelmunoz00** [mgallegos/laravel-jqgrid#63]
Hola,

Como y donde puedo agregar el método para hacer doble click en una fila y que aparezca el formulario de edición ?

Muchas gracias.

**Comment by mgallegos** [comment]
Hola, para [habilitar el método lo puedes](http://www.trirand.com/jqgridwiki/doku.php?id=wiki:events&s[]=ondblclickrow) hacer así:

```
  ->setGridEvent('ondblClickRow', 'elNombreDeTuFuncionJavaScript') 
```

**Comment by manuelmunoz00** [comment]
Hola, muchas gracias por la info. Encontré una alternativa para editar los campos en la misma fila y no al levantar el formulario. Dejar el siguiente código en la sección javascript. Para quien le sea de utilidad.

$(document).ready(function(){
		var grid=$('#myFirstGrid');
		$(grid).jqGrid('setGridParam',{ 
			ondblClickRow: function(){
				var row_id = $(grid).getGridParam('selrow');
				jQuery(grid).editRow(row_id, true);
			}
		});
	});

Saludos y gracias nuevamente.
