### ISSUE TITLE
UTF8 encoding isssue

### ISSUE THREAD

**Issue by sroutier** [mgallegos/laravel-jqgrid#70]
Hello Mario,

Can we discuss your last patch and release please?

With the call on line 252 of JqGridJsonEncoder.php to utf8ize commented out some data may not be properly converted and exported.

For example see the screen shot below:
![2017-03-21_9-41-02](https://cloud.githubusercontent.com/assets/3011606/24150086/2827a3a0-0e1b-11e7-90a8-6d45a2c499d6.png)

The XLS and CSV export files from both version 1.2.0 and 1.2.1 are attached and included in the zip file below.
[reportPmpRoles.zip](https://github.com/mgallegos/laravel-jqgrid/files/858301/reportPmpRoles.zip)

You can see that the mission column renders properly on the screen but version 1.2.1 does not export them properly.

I really think that line 252 is required.

Thanks.
/S

**Comment by mgallegos** [comment]
Of course, the problem that I'm having on my applications is that with the line I commented, all words with accents such as Bogotá appears with encoding issues on the screen.

Until you pointed out I haven't had any issue with such characters in the grid or CVS, XLS format.

**Comment by sroutier** [comment]
What? Did I understand you correctly:
Are you saying that with line 252 your screen is not properly rendered? 
And without it, I am having issues with the file export? 
That is not good... 

Have you tested exporting data? What does it look like for both versions?
What kind of database is your data coming from? Mine is from MS SQL Server?
What browser are you using? Are you using some specific text encoding on your browser?

I hate those character encoding issues....

/s

**Comment by mgallegos** [comment]
> Are you saying that with line 252 your screen is not properly rendered?

Yes!

> Have you tested exporting data? What does it look like for both versions?

Same problem when exporting

> What kind of database is your data coming from? 

MySQL but the database is on UTF8, what about yours?

@sroutier, one solution that could help, is to add a property in the JqGridJsonEncoder as false by default, to be set to true when utf8ize is needed, what do you think?

**Comment by sroutier** [comment]
I agree with your recommendation of adding a property in the JqGridJsonEncoder, I was just thinking about that.
In the mean time, let me contact our database administrator to get a bit more info on the encoding used in our database, that way we can compare, but the property looks like the right fix.

/s

**Comment by mgallegos** [comment]
Please let me know if this changes works for you: a7388f8

If it does I will publish a new release.

**Comment by isaqueprofeta** [comment]
@mgallegos, using [a7388f8](https://github.com/mgallegos/laravel-jqgrid/commit/a7388f8b3b28ef542741f23bc8b01ad5e07a254a) solved for me like a charm on grid table and xls/csv export too.

**Comment by mgallegos** [comment]
I'm glad to hear that @isaqueprofeta
