### ISSUE TITLE
Whoops, looks like something went wrong.

### ISSUE THREAD

**Issue by T3KN0KRAT** [mgallegos/laravel-jqgrid#71]
It appears that the tutorial page at http://www.mariogallegos.com/tutorials/pivot-grid is not working. 

Actually, none of them are:
http://www.mariogallegos.com/tutorials/crud-jqgrid-form
http://www.mariogallegos.com/tutorials/crud-custom-form

Likewise for the demos:
http://www.mariogallegos.com/open-source-development/laravel-jqgrid/demo[1-3]

**Comment by mgallegos** [comment]
Sorry @T3KN0KRAT, but I haven't got time yet to fix this, I hope I'll do it soon.

**Comment by T3KN0KRAT** [comment]
Thanks!  I'm really looking forward to seeing those examples.

**Comment by liline** [comment]
Thanks for making this. I'm also looking forward to seeing these examples!
