### ISSUE TITLE
Live Demos throwing 404 exception.

### ISSUE THREAD

**Issue by younus93** [mgallegos/laravel-jqgrid#75]
The mentioned live demo links in the website throws a 404 exception. 

```
There are three demos available:

Pivot Grid
CRUD Web App with jqGrid forms
CRUD Web App with a custom form

```

**Comment by mgallegos** [comment]
Thanks, fix the only one that's available at the moment:

http://www.mariogallegos.com/cms/open-source-development/laravel-jqgrid/demo3
